#!/usr/bin/python3

import subprocess
import os
import shutil
import sys

clean_project = False
if len(sys.argv) == 2 and sys.argv[1] == "--clean":
  clean_project = True

if clean_project:
  print("Cleaning project before building")
  subprocess.run(["conan", "remove", "grumble", "-c"])

  if os.path.isdir("build"):
    shutil.rmtree("build")

  if os.path.isdir("CMakeFiles"):
    shutil.rmtree("CMakeFiles")

subprocess.run(["conan", "install", "." ,"--output-folder=build", "--build=missing"])

os.chdir("build")

subprocess.run([
    "cmake", 
    "..", 
    "-DCMAKE_TOOLCHAIN_FILE='conan_toolchain.cmake'",
    "-DCMAKE_BUILD_TYPE=Debug", 
    "-DCMAKE_EXPORT_COMPILE_COMMANDS=1"
])

subprocess.run(["cmake", "--build", ".", "--config Debug"])

os.chdir("..")
subprocess.run(["conan", "export-pkg", ".", "--output-folder" , "conan"])
